### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by LumineRose** [hiperiondev/hpsdr-rpitx#1]
(root??kali)-[~/hpsdr-rpitx/build]
??# make                                                                     
Building file: ../librpitx/modulation/amdmasync.cpp
Invoking: Cross G++ Compiler
g++ -std=c++0x -I"/home/opt/Desarrollos/workspace-rpitx/hpsdr-rpitx/librpitx" -I"/home/opt/Desarrollos/workspace-rpitx/hpsdr-rpitx/librpitx/core/include" -I"/home/opt/Desarrollos/workspace-rpitx/hpsdr-rpitx/librpitx/modulation/include" -I"/home/opt/Desarrollos/workspace-rpitx/hpsdr-rpitx/hpsdr/include" -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"librpitx/modulation/amdmasync.d" -MT"librpitx/modulation/amdmasync.o" -o "librpitx/modulation/amdmasync.o" "../librpitx/modulation/amdmasync.cpp"
../librpitx/modulation/amdmasync.cpp:25:10: fatal error: gpio.hpp: No such file or directory
   25 | #include "gpio.hpp"
      |          ^~~~~~~~~~
compilation terminated.
make: *** [librpitx/modulation/subdir.mk:47: librpitx/modulation/amdmasync.o] Error 1

**Comment by hiperiondev** [comment]
I have corrected build.
Please retry
