### ISSUE TITLE
"hpsdr-rpitx: command not found" 

### ISSUE THREAD

**Issue by LumineRose** [hiperiondev/hpsdr-rpitx#2]
"hpsdr-rpitx: command not found"
after installation
"COMPILE PROJECT:

git clone https://github.com/hiperiondev/hpsdr-rpitx.git
cd hpsdr-rpitx/build
make
USE: hpsdr-rpitx [flags]"

**Comment by hiperiondev** [comment]
If hpsdr-rpitx is not in PATH you need to use full path or , in hpsdr-rpitx/build: ./hpsdr-rpitx

**Comment by LumineRose** [comment]
After input, nothing happens, no matter what flags are used (Rpi 3b, os kali linux 2021)

**Comment by hiperiondev** [comment]
If you add -debug flag will see all messages. Without this flag the program is in quiet mode
